### ISSUE TITLE
[BUG] Unable develop and run localhost

### ISSUE THREAD

**Issue by noinarisak** [udplabs/zartan#74] opened 2020-04-21 15:02 UTC
**Describe the bug**
Expected to be able to develop and run a local instance on my mac. Zartan assumes that you have already been configured/connected to UDP infrastructure. As a contributor/developer, I want to be able to locally run the Zartan without UDP. 

**To Reproduce**
N/A

**Expected behavior**
Run localhost instance on my development box.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version: 80

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by srecinto** [comment] 2020-04-22 03:04
Looks like a duplicate of #71 please confirm it is fixed

**Closed** 2020-04-22 17:11 UTC
